/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContactInfo = IDL.Record({
  'email' : IDL.Text,
  'affiliation' : IDL.Text,
});
export const ProfileData = IDL.Record({
  'name' : IDL.Text,
  'biography' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
});
export const Time = IDL.Int;
export const Publication = IDL.Record({
  'id' : IDL.Text,
  'pdf' : IDL.Opt(ExternalBlob),
  'title' : IDL.Text,
  'link' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'timestamp' : Time,
});
export const ResearchInterest = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPublication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob)],
      [IDL.Text],
      [],
    ),
  'addResearchInterest' : IDL.Func([IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearData' : IDL.Func([], [], []),
  'deletePublication' : IDL.Func([IDL.Text], [], []),
  'deleteResearchInterest' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactInfo' : IDL.Func([], [IDL.Opt(ContactInfo)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(ProfileData)], ['query']),
  'getPublication' : IDL.Func([IDL.Text], [Publication], ['query']),
  'getPublications' : IDL.Func([], [IDL.Vec(Publication)], ['query']),
  'getResearchInterests' : IDL.Func([], [IDL.Vec(ResearchInterest)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isOwner' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setContactInfo' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'updatePublication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContactInfo = IDL.Record({
    'email' : IDL.Text,
    'affiliation' : IDL.Text,
  });
  const ProfileData = IDL.Record({
    'name' : IDL.Text,
    'biography' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const Time = IDL.Int;
  const Publication = IDL.Record({
    'id' : IDL.Text,
    'pdf' : IDL.Opt(ExternalBlob),
    'title' : IDL.Text,
    'link' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'timestamp' : Time,
  });
  const ResearchInterest = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPublication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob)],
        [IDL.Text],
        [],
      ),
    'addResearchInterest' : IDL.Func([IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearData' : IDL.Func([], [], []),
    'deletePublication' : IDL.Func([IDL.Text], [], []),
    'deleteResearchInterest' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactInfo' : IDL.Func([], [IDL.Opt(ContactInfo)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(ProfileData)], ['query']),
    'getPublication' : IDL.Func([IDL.Text], [Publication], ['query']),
    'getPublications' : IDL.Func([], [IDL.Vec(Publication)], ['query']),
    'getResearchInterests' : IDL.Func(
        [],
        [IDL.Vec(ResearchInterest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isOwner' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setContactInfo' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'updatePublication' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };