/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactInfo { 'email' : string, 'affiliation' : string }
export type ExternalBlob = Uint8Array;
export interface ProfileData {
  'name' : string,
  'biography' : string,
  'photo' : [] | [ExternalBlob],
}
export interface Publication {
  'id' : string,
  'pdf' : [] | [ExternalBlob],
  'title' : string,
  'link' : [] | [string],
  'description' : string,
  'timestamp' : Time,
}
export interface ResearchInterest { 'id' : string, 'name' : string }
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPublication' : ActorMethod<
    [string, string, [] | [string], [] | [ExternalBlob]],
    string
  >,
  'addResearchInterest' : ActorMethod<[string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearData' : ActorMethod<[], undefined>,
  'deletePublication' : ActorMethod<[string], undefined>,
  'deleteResearchInterest' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInfo' : ActorMethod<[], [] | [ContactInfo]>,
  'getProfile' : ActorMethod<[], [] | [ProfileData]>,
  'getPublication' : ActorMethod<[string], Publication>,
  'getPublications' : ActorMethod<[], Array<Publication>>,
  'getResearchInterests' : ActorMethod<[], Array<ResearchInterest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isOwner' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setContactInfo' : ActorMethod<[string, string], undefined>,
  'setProfile' : ActorMethod<[string, string, [] | [ExternalBlob]], undefined>,
  'updatePublication' : ActorMethod<
    [string, string, string, [] | [string], [] | [ExternalBlob]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];